/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
  obsScenes: {
    gameLayout: string;
  };
  obsVirtualScenes: {
    capture1: string;
    capture2: string;
    capture3: string;
    capture4: string;
    camera1: string;
    camera2: string;
  };
  obsSources: {
    rack1: string;
    rack2: string;
    rack3: string;
    rack4: string;
    camSource1: string;
    camSource2: string;
  };
  emergencyMode: {
    scene: string;
    audioSource: string;
  };
}
